// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import React from 'react';
import { createRoot } from 'react-dom/client';
import './index.css';
import App from './app/App';
import { SwitchableFluentThemeProvider } from './app/theming/SwitchableFluentThemeProvider';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
const queryClient = new QueryClient();
const domNode = document.getElementById('root');
if (!domNode) {
  throw new Error('Failed to find the root element');
}

createRoot(domNode).render(
  <React.StrictMode>
    <SwitchableFluentThemeProvider scopeId="SampleCallingApp">
    <QueryClientProvider client={queryClient}>
      <div className="wrapper">
        <App />
      </div>
      </QueryClientProvider>
    </SwitchableFluentThemeProvider>
  </React.StrictMode>
);
export {}; /*The above line is generated by conditional compilation, when no export detected after CC.*/
